import type { InvitedBy, Priority } from '../guests/guest.entity';

export interface SeedGuest {
  id: string;
  includedBy: string;
  nameOnInvitation: string;
  firstName: string;
  lastName: string;
  guestType: string;
  priority: Priority;
  invitedBy: InvitedBy;
  hasInvite: boolean;
}

// Column order: id, includedBy, nameOnInvitation, firstName, lastName,
//               guestType, priority, invitedBy, hasInvite
//
// Refreshed 2026-08-08 from the couple's masterlist. In this revision the
// grouping labels (e.g. "Atty. Walter Avillanosa", "Uncle Josef") live in
// `nameOnInvitation`; `includedBy` is unused (blank) throughout. See the
// 2026-08-08-guest-masterlist-refresh migration for the exact diff applied.
type Row = [
  string,
  string,
  string,
  string,
  string,
  string,
  Priority,
  InvitedBy,
  boolean,
];

const rows: Row[] = [
  ['G-0001', '', 'Mama', 'Janette', 'Avillanosa', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0002', '', 'Papa', 'Alan', 'Avillanosa', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0003', '', 'Kuya Caloy', 'Carl Ace', 'Avillanosa', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0004', '', 'Ate Joelle', 'Joelle', 'Avillanosa', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0005', '', 'Ate Anika', 'Anika', 'Avillanosa - Rose', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0006', '', 'Kuya Glenn', 'Glenn Ace', 'Rose', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0007', '', 'Spike', 'Spike', 'Avillanosa', '🥇Family Member', 'Important Person', 'Groom', true],
  ['G-0008', '', 'Kelly', 'Kelly', 'Fernandez', '🥉Extended family member', 'Important Person', 'Groom', true],
  ['G-0009', '', 'JHOMAR EDEP ZABALO', 'Jhomar', 'Zabalo', '🤵‍♂️ Best Man', 'Important Person', 'Groom', true],
  ['G-0010', '', 'Ride or die brother for life', 'Jesse', 'Canonigo', '👞 Abay (Male)', 'Important Person', 'Groom', false],
  ['G-0011', '', '', 'Rey', 'Omiple', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0012', '', '', 'Ariel', 'Dancil', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0013', '', '', 'Arvie', 'Cabatingan', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0014', '', '', 'John', 'Salvame', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0015', '', '', 'Brylle', 'Romualdo', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0016', '', '', 'Julius', 'Tan', '👞 Abay (Male)', '', 'Groom', true],
  ['G-0017', '', '', 'Ritchell', 'Asuero', '🥈 Friends', '', 'Groom', true],
  ['G-0018', '', '', 'Mhay', 'Arenio', '🥈 Friends', 'Unsure', 'Groom', true],
  ['G-0019', '', '', 'Cherry', 'Asotilla', 'Regular Guest', 'Unsure', 'Groom', true],
  ['G-0020', '', '', 'Itchu', 'Atanacio', '🥉Extended family member', '', 'Groom', true],
  ['G-0021', '', '', 'Jojo', 'Atanacio', '🥉Extended family member', '', 'Groom', true],
  ['G-0022', '', '', 'Boy', 'Patino', '🥉Extended family member', '', 'Groom', true],
  ['G-0023', '', '', 'Pipit', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0024', '', '', 'Rona', 'Relampagos', '🎀Ninang', 'Unsure', 'Groom', true],
  ['G-0025', '', '', 'Juanito', 'Relampagos', '🍺 Ninong', 'Unsure', 'Groom', true],
  ['G-0026', '', '', 'Arman', 'Solpico', '🍺 Ninong', 'Important Person', 'Groom', true],
  ['G-0027', '', '', 'May', 'Aaron-Solpico', '🎀Ninang', 'Important Person', 'Groom', true],
  ['G-0028', '', '', 'Joshua', 'Saac', '🍺 Ninong', 'Important Person', 'Groom', true],
  ['G-0029', '', '', 'Princess Shaira', 'Abo-Abo', '🎀Ninang', 'Important Person', 'Groom', true],
  ['G-0030', '', '', 'Celso', 'Ducao', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0031', '', '', 'Gillou', 'Carbonell', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0032', '', '', 'Arvy', 'Mayor', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0033', '', '', 'Oh', 'Pimentel', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0034', '', '', 'Cedie', 'Gabinete', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0035', '', '', 'Jan', 'Dulla', '💼 Previous Colleagues', 'Unsure', 'Groom', true],
  ['G-0036', '', '', 'Criz', 'Oligo', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0037', '', '', 'Andrew', 'Francisco', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0038', '', '', 'Jan Erick', 'Santos', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0039', '', '', 'Nico', 'Aplino', '💼 Previous Colleagues', 'Unsure', 'Groom', true],
  ['G-0040', '', '', 'Wendell', 'Saac', '💼 Previous Colleagues', 'Regular', 'Groom', true],
  ['G-0041', '', '', 'Virginia', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0042', '', 'Atty. Walter Avillanosa', 'Walter', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0043', '', 'Atty. Iris Avillanosa', 'Iris', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0044', '', 'Tito Toots', 'Augustus', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0045', '', 'Tita Arlene', 'Arlene', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0046', '', 'Abby', 'Abigail Vivien', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0047', '', 'Ate Baye', 'Gabrielle', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0048', '', 'Laki', 'Andre Kim', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0049', '', 'Tony', 'Walton Karl', 'Avillanosa', '🥉Extended family member', '', 'Groom', true],
  ['G-0050', '', 'Atty. Alex Rivera', 'Alexander', 'Rivera', '🥉Extended family member', 'Unsure', 'Groom', true],
  ['G-0051', '', '', 'Jackie', 'Rivera-Pastrana', '🥉Extended family member', '', 'Groom', true],
  ['G-0052', '', '', 'Jonie', 'Pastrana', '🥉Extended family member', '', 'Groom', true],
  ['G-0053', '', '', 'Marina', 'Pasion', '🥇Family Member', 'Important Person', 'Bride', true],
  ['G-0054', '', '', 'Valentino', 'Pasion', '🥇Family Member', 'Important Person', 'Bride', true],
  ['G-0055', '', '', 'Kathleen Joy', 'Pasion', '🥇Family Member', 'Important Person', 'Bride', true],
  ['G-0056', '', '', 'David Steven', 'Grench', '🥉Extended family member', 'Important Person', 'Bride', true],
  ['G-0057', '', '', 'Cristine May', 'Pasion', '🥇Family Member', 'Important Person', 'Bride', true],
  ['G-0058', '', '', 'Eurichris', 'Sergio', '🥉Extended family member', '', 'Bride', true],
  ['G-0059', '', '', 'Liezel', 'Espelita', '👰🏻Maid of honor', '', 'Bride', true],
  ['G-0060', '', '', 'Kariz Jane', 'Zandueta', '👗Abay (Female)', '', 'Bride', true],
  ['G-0061', '', '', 'Loradel', 'Pederano', '👗Abay (Female)', '', 'Bride', true],
  ['G-0062', '', '', 'Mariam', 'Elesterio', '👗Abay (Female)', '', 'Bride', false],
  ['G-0063', '', '', 'Camille', 'Cadigal', '👗Abay (Female)', '', 'Bride', true],
  ['G-0064', '', 'Caye', 'Caye Jhaycez', 'Chua', '👗Abay (Female)', '', 'Bride', true],
  ['G-0065', '', '', 'Kaye', 'Andao', '🥉Extended family member', '', 'Bride', false],
  ['G-0066', '', '', 'Yossef', 'Persov', '🍺 Ninong', 'Unsure', 'Bride', true],
  ['G-0067', '', '', 'Flexie Joe', 'Magabo', '🎀Ninang', '', 'Bride', true],
  ['G-0068', '', '', 'Larry', 'Ylaya', '🍺 Ninong', 'Unsure', 'Bride', true],
  ['G-0069', '', '', 'Batangas', 'Melinda', '💼 Previous Colleagues', 'Unsure', 'Bride', true],
  ['G-0070', '', '', 'Batangas', 'Mae', '💼 Previous Colleagues', 'Unsure', 'Bride', true],
  ['G-0071', '', '', 'Batangas', 'Iban', '💼 Previous Colleagues', 'Unsure', 'Bride', false],
  ['G-0072', '', '', 'Batangas', 'Vanessa', '💼 Previous Colleagues', 'Unsure', 'Bride', true],
  ['G-0073', '', '', 'Kuya Randy', 'Andao', '🥉Extended family member', 'Unsure', 'Bride', false],
  ['G-0074', '', '', 'Jacob', 'Urette', '🥈 Friends', 'Unsure', 'Bride', true],
  ['G-0075', '', '', 'Peter', 'Nepomuceno', '🥈 Friends', 'Unsure', 'Bride', true],
  ['G-0076', '', '', 'Fu', 'Muhammad', '🥈 Friends', 'Unsure', 'Bride', false],
  ['G-0077', '', '', 'Nelia', 'Andao', '🥉Extended family member', '', 'Bride', true],
  ['G-0078', '', '', 'Isidro', 'Andao', '🥉Extended family member', '', 'Bride', true],
  ['G-0079', '', 'Uncle Josef', 'Joseph', 'Andao', '🥉Extended family member', '', 'Bride', true],
  ['G-0080', '', 'Uncle Boying', 'Boying', 'Pasion', '🥉Extended family member', '', 'Bride', true],
  ['G-0081', '', '', 'Kuya Jason', 'Andao', '🥉Extended family member', '', 'Bride', false],
  ['G-0082', '', '', 'Raquel', 'Andao', '🥉Extended family member', 'Unsure', 'Bride', false],
  ['G-0083', '', '', 'Ate Fe', 'Herman', 'Regular Guest', '', 'Bride', false],
  ['G-0084', '', '', 'Ate Marie', 'Herman', 'Regular Guest', '', 'Bride', false],
  ['G-0085', '', '', 'Ante Chit', 'Dela Cruz', 'Regular Guest', '', 'Bride', true],
  ['G-0086', '', '', 'Ninong', 'Eddie', '🥉Extended family member', '', 'Bride', true],
  ['G-0087', '', '', 'Auntie', 'Lettie', 'Regular Guest', '', 'Bride', true],
  ['G-0088', '', '', 'Nang Anit', '', 'Regular Guest', '', 'Bride', true],
  ['G-0089', '', '', 'Kuya Edward', 'Pasion', '🥉Extended family member', '', 'Bride', false],
  ['G-0090', '', '', 'Ate Kambal', 'Pasion', '🥉Extended family member', '', 'Bride', false],
  ['G-0091', '', 'Ate tin', 'Cristine', 'Celedonio', '👗Abay (Female)', '', 'Bride', false],
  ['G-0092', '', 'Kuya Dambok', 'Danvir', 'Quicho', '🥉Extended family member', '', 'Bride', true],
  ['G-0093', '', 'Ate dalin', 'Ate dalin', 'Quicho', '🥉Extended family member', '', 'Bride', false],
  ['G-0094', '', 'Tita Shonie', 'Siony', 'Ungoco', '🥉Extended family member', '', 'Bride', false],
  ['G-0095', '', 'Tita Perz', 'Percival', 'Pasion', '🥉Extended family member', '', 'Bride', true],
  ['G-0096', '', 'Tita Vergie', 'Tita Vergie', 'Quicho', '🥉Extended family member', '', 'Bride', false],
  ['G-0097', '', 'Kuya Ayoy', 'Ate titin', 'Pasion', '🥉Extended family member', '', 'Bride', false],
  ['G-0098', '', 'Jake Andao', 'Jake', 'Andao', '🥉Extended family member', '', 'Bride', false],
  ['G-0099', '', 'Ate Quenie', 'Ate Quenie', '', '🥉Extended family member', '', 'Bride', true],
  ['G-0100', '', 'Nene Andao', 'Aisil', 'Andao', '🥉Extended family member', '', 'Bride', false],
  ['G-0101', '', 'Ate Minerva', 'Ate Minerva', '', 'Regular Guest', '', 'Bride', false],
  ['G-0102', '', 'Tim Marapao', 'Tim', 'Marapao', '🥈 Friends', '', 'Groom', false],
  // Added 2026-09-21. Extended family, invited by the groom.
  ['G-0106', '', 'Ate Ana', 'Ana', '', '🥉Extended family member', '', 'Groom', false],
  ['G-0107', '', 'Ate Ritchelle', 'Ritchelle', 'Rebleza Gomez', '🥉Extended family member', '', 'Groom', false],
  ['G-0108', '', '', 'Renalyn', 'Cauntao', '🥉Extended family member', '', 'Groom', false],
  ['G-0109', '', '', 'Claire', 'Detera', '🥉Extended family member', '', 'Groom', false],
];

export const seedGuests: SeedGuest[] = rows.map(
  ([
    id,
    includedBy,
    nameOnInvitation,
    firstName,
    lastName,
    guestType,
    priority,
    invitedBy,
    hasInvite,
  ]) => ({
    id,
    includedBy,
    nameOnInvitation,
    firstName,
    lastName,
    guestType,
    priority,
    invitedBy,
    hasInvite,
  }),
);
